include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat all issues as warnings to prevent blocking builds
    unused_local_variable: warning
    dead_code: warning

linter:
  rules:
    # Add additional lint rules if needed
    prefer_final_locals: true
    avoid_print: true
    type_annotate_public_apis: true
    always_specify_types: true
