dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.3
  flutter_localizations:
    sdk: flutter
  http: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  async: ^2.12.0
  boolean_selector: ^2.1.2
  clock: ^1.1.2
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  test_api: ^0.7.4
  vm_service: ^15.0.0

environment:
  sdk: ^3.5.0

flutter:
  uses-material-design: true
